name: Jekyll Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Update _config.yaml
      run: |
        sed -i -e 's/env: dev/env: prod/' _config.yml
    - name: Build and Deploy
      run: |
        jekyll build --branch gh-pages
      env:
        JEKYLL_ENV: production
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
